#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================
 
# 取消 lan 动态 DHCP
uci set dhcp.lan.dynamicdhcp='0'

# 禁用 IPv6 https://www.cnblogs.com/NueXini/p/15707858.html
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ra
uci delete dhcp.lan.ra_slaac
uci delete dhcp.lan.ra_flags
uci set dhcp.@dnsmasq[0].filter_aaaa='1'

# 时区设置
uci set system.@system[0].zonename='Asia/Shanghai'

# 保存到文件
uci commit

#exit 0