#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Docker Images

env:
  DEVICE_VERSION: 24.10.2

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  Docker-Images:
    name: Build OpenWrt Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 genisoimage zstd 

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Download Image Builder
        run: |
          wget -q https://downloads.openwrt.org/releases/$DEVICE_VERSION/targets\
          /x86/64/openwrt-imagebuilder-$DEVICE_VERSION-x86-64.Linux-x86_64.tar.zst

      - name: Set Image Builder
        run: |
          tar -I zstd -xvf *.tar.zst
          cd openwrt-imagebuilder-$DEVICE_VERSION-x86-64.Linux-x86_64
          cp -rf $GITHUB_WORKSPACE/files .
          chmod +x files/etc/rc.local

      - name: Build RootFS
        run: |
          cd openwrt-imagebuilder-$DEVICE_VERSION-x86-64.Linux-x86_64
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/scripts/preset-terminal-tools.sh
          export CONFIG_PACKAGES=$(cat $GITHUB_WORKSPACE/config/packages.config | tr -s "\n" " ")
          make image PACKAGES="$CONFIG_PACKAGES" FILES="files"
          cp -rf bin/targets/x86/64/*rootfs.tar.gz $GITHUB_WORKSPACE

      - name: Delete Image Builder
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf openwrt-imagebuilder*

      - name: Build & Push Tiny Image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/openwrt
            
      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          file: alpha/Dockerfile
          context: alpha
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/openwrt:alpha
